[versions]
java = "21"
axon-bom = "4.12.2"
axon-framework = "4.12.2"
spring-boot = "3.5.8"
spring-framework-bom = "6.2.14"
spring-data-bom = "2025.0.6"
spring-data-opensearch = "2.0.3"
springdoc-openapi-starter = "2.8.14"
swagger = "2.2.41"
swagger-ui = "5.30.3"
postgresql = "42.7.8"
flyway = "11.18.0"
caffeine = "3.2.3"
db-scheduler = "13.0.0"
mapstruct = "1.6.3"
jackson-bom = "2.20.1"
reactor-bom = "2025.0.0"
reactor-kafka = "1.3.25"
reactor-blockhound = "1.0.15.RELEASE"
netty-bom = "4.2.7.Final"
resilience4j-bom = "2.3.0"
streamex = "0.8.4"
jgroups = "4.2.30.Final"
jgroups-kubernetes = "1.0.17.Final"
protobuf = "4.33.1"
elasticsearch-client = "9.2.1"
opensearch = "4.0.0"
opensearch-client = "3.3.0"
micrometer-bom = "1.16.0"
micrometer-tracing-bom = "1.6.0"
opentelemetry-bom = "1.56.0"
commons-compress = "1.28.0"
commons-fileupload = "1.6.0"
commons-lang3 = "3.20.0"
commons-io = "2.21.0"
expressly = "6.0.0"
guava = "33.5.0-jre"
log4j = "2.25.2"
logback = "1.5.21"
xstream = "1.4.21"
ksuid = "1.1.4"
jakarta-validation-api = "3.1.1"
jspecify = "1.0.0"
hamcrest = "3.0"
mockito-bom = "5.20.0"
wiremock-spring-boot = "4.0.8"
kotlin = "2.2.21"
errorprone = "2.45.0"
nullaway = "0.12.13"
spotbugs = "4.9.8"
lombok = "1.18.42"
lombok-plugin = "9.1.0"
protobuf-plugin = "0.9.5"
gatling-plugin = "3.14.9"
dependencyVersions-plugin = "0.53.0"
errorprone-plugin = "4.3.0"
spotbugs-plugin = "6.3.0"
spotbugs-findsecbugs-plugin = "1.14.0"
spotbugs-fbContrib-plugin = "7.7.1"
helm = "4.0.0"
helm-plugin = "2.2.0"
bitnami-common = "2.x.x"
bitnami-postgresql = "16.x.x"
bitnami-kafka = "31.x.x"
bitnami-opensearch = "2.x.x"
prometheus-community-stack = "77.x.x"
grafana-tempo = "1.x.x"
postgres-image = "17"
kafka-image = "3.9.1"
opensearch-image = "3"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-autoconfigure = { group = "org.springframework.boot", name = "spring-boot-autoconfigure" }
spring-boot-starter-aop = { group = "org.springframework.boot", name = "spring-boot-starter-aop" }
spring-boot-starter-cache = { group = "org.springframework.boot", name = "spring-boot-starter-cache" }
spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc" }
spring-boot-starter-webflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }
spring-framework-bom = { group = "org.springframework", name = "spring-framework-bom", version.ref = "spring-framework-bom" }
spring-data-bom = { group = "org.springframework.data", name = "spring-data-bom", version.ref = "spring-data-bom" }
spring-data-commons = { group = "org.springframework.data", name = "spring-data-commons" }
spring-data-jdbc = { group = "org.springframework.data", name = "spring-data-jdbc" }
spring-data-opensearch = { group = "org.opensearch.client", name = "spring-data-opensearch", version.ref = "spring-data-opensearch" }
spring-data-opensearch-starter = { group = "org.opensearch.client", name = "spring-data-opensearch-starter", version.ref = "spring-data-opensearch" }
spring-data-opensearch-testcontainers = { group = "org.opensearch.client", name = "spring-data-opensearch-testcontainers", version.ref = "spring-data-opensearch" }
springdoc-openapi-starter-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springdoc-openapi-starter" }
elasticsearch-client-java = { group = "co.elastic.clients", name = "elasticsearch-java", version.ref = "elasticsearch-client" }
opensearch-client-java = { group = "org.opensearch.client", name = "opensearch-java", version.ref = "opensearch-client" }
opensearch-client-restHighLevel = { group = "org.opensearch.client", name = "opensearch-rest-high-level-client", version.ref = "opensearch-client" }
swagger-annotations-jakarta = { group = "io.swagger.core.v3", name = "swagger-annotations-jakarta", version.ref = "swagger" }
swagger-core-jakarta = { group = "io.swagger.core.v3", name = "swagger-core-jakarta", version.ref = "swagger" }
swagger-models-jakarta = { group = "io.swagger.core.v3", name = "swagger-models-jakarta", version.ref = "swagger" }
swagger-ui = { group = "org.webjars", name = "swagger-ui", version.ref = "swagger-ui" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }
commons-fileupload = { group = "commons-fileupload", name = "commons-fileupload", version.ref = "commons-fileupload" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
hibernate-validator = { group = "org.hibernate.validator", name = "hibernate-validator" }
expressly = { group = "org.glassfish.expressly", name = "expressly", version.ref = "expressly" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
resilience4j-bom = { group = "io.github.resilience4j", name = "resilience4j-bom", version.ref = "resilience4j-bom" }
resilience4j-all = { group = "io.github.resilience4j", name = "resilience4j-all" }
resilience4j-reactor = { group = "io.github.resilience4j", name = "resilience4j-reactor" }
resilience4j-springBoot3 = { group = "io.github.resilience4j", name = "resilience4j-spring-boot3" }
streamex = { group = "one.util", name = "streamex", version.ref = "streamex" }
jgroups = { group = "org.jgroups", name = "jgroups", version.ref = "jgroups" }
jgroups-kunernetes = { group = "org.jgroups.kubernetes", name = "jgroups-kubernetes", version.ref = "jgroups-kubernetes" }
protobuf-bom = { group = "com.google.protobuf", name = "protobuf-bom", version.ref = "protobuf" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql" }
testcontainers-kafka = { group = "org.testcontainers", name = "kafka" }
testcontainers-opensearch = { group = "org.opensearch", name = "opensearch-testcontainers", version.ref = "opensearch" }
log4j-api = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }
log4j-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
log4j-toSlf4j = { group = "org.apache.logging.log4j", name = "log4j-to-slf4j", version.ref = "log4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson-bom" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind" }
jackson-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310" }
jackson-module-blackbird = { group = "com.fasterxml.jackson.module", name = "jackson-module-blackbird" }
xstream = { group = "com.thoughtworks.xstream", name = "xstream", version.ref = "xstream" }
assertj-core = { group = "org.assertj", name = "assertj-core" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
mockito-bom = { group = "org.mockito", name = "mockito-bom", version.ref = "mockito-bom" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-bom" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter" }
reactor-bom = { group = "io.projectreactor", name = "reactor-bom", version.ref = "reactor-bom" }
reactor-core = { group = "io.projectreactor", name = "reactor-core" }
reactor-core-micrometer = { group = "io.projectreactor", name = "reactor-core-micrometer" }
reactor-extra = { group = "io.projectreactor.addons", name = "reactor-extra" }
reactor-kafka = { group = "io.projectreactor.kafka", name = "reactor-kafka", version.ref = "reactor-kafka" }
reactor-test = { group = "io.projectreactor", name = "reactor-test" }
reactor-tools = { group = "io.projectreactor", name = "reactor-tools" }
reactor-blockhound = { group = "io.projectreactor.tools", name = "blockhound", version.ref = "reactor-blockhound" }
netty-bom = { group = "io.netty", name = "netty-bom", version.ref = "netty-bom" }
netty-resolver-dnsNativeMacos = { group = "io.netty", name = "netty-resolver-dns-native-macos" }
wiremock-springBoot = { group = "org.wiremock.integrations", name = "wiremock-spring-boot", version.ref = "wiremock-spring-boot" }
axon-bom = { group = "org.axonframework", name = "axon-bom", version.ref = "axon-bom" }
axon-modelling = { group = "org.axonframework", name = "axon-modelling", version.ref = "axon-framework" }
axon-messaging = { group = "org.axonframework", name = "axon-messaging", version.ref = "axon-framework" }
axon-springBoot-starter = { group = "org.axonframework", name = "axon-spring-boot-starter", version.ref = "axon-framework" }
axon-serverConnector = { group = "org.axonframework", name = "axon-server-connector", version.ref = "axon-framework" }
axon-micrometer = { group = "org.axonframework", name = "axon-micrometer", version.ref = "axon-framework" }
axon-tracing-opentelemetry = { group = "org.axonframework", name = "axon-tracing-opentelemetry", version.ref = "axon-framework" }
axon-extensions-kafka = { group = "org.axonframework.extensions.kafka", name = "axon-kafka" }
axon-extensions-kafka-springBootStarter = { group = "org.axonframework.extensions.kafka", name = "axon-kafka-spring-boot-starter" }
axon-extensions-jgroups-springBootStarter = { group = "org.axonframework.extensions.jgroups", name = "axon-jgroups-spring-boot-starter" }
axon-extensions-reactor-springBootStarter = { group = "org.axonframework.extensions.reactor", name = "axon-reactor-spring-boot-starter" }
axon-test = { group = "org.axonframework", name = "axon-test", version.ref = "axon-framework" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
caffeine-jcache = { group = "com.github.ben-manes.caffeine", name = "jcache", version.ref = "caffeine" }
dbScheduler-springBootStarter = { group = "com.github.kagkarlsson", name = "db-scheduler-spring-boot-starter", version.ref = "db-scheduler" }
micrometer-bom = { group = "io.micrometer", name = "micrometer-bom", version.ref = "micrometer-bom" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus" }
micrometer-registry-otlp = { group = "io.micrometer", name = "micrometer-registry-otlp" }
micrometer-tracing-bom = { group = "io.micrometer", name = "micrometer-tracing-bom", version.ref = "micrometer-tracing-bom" }
micrometer-tracing-bridge-otel = { group = "io.micrometer", name = "micrometer-tracing-bridge-otel" }
opentelemetry-bom = { group = "io.opentelemetry", name = "opentelemetry-bom", version.ref = "opentelemetry-bom" }
opentelemetry-exporter-otlp = { group = "io.opentelemetry", name = "opentelemetry-exporter-otlp" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakarta-validation-api" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
ksuid = { group = "com.github.ksuid", name = "ksuid", version.ref = "ksuid" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
lombok-plugin = { group = "io.freefair.gradle", name = "lombok-plugin", version.ref = "lombok-plugin" }
spring-boot-plugin = { group = "org.springframework.boot", name = "spring-boot-gradle-plugin", version.ref = "spring-boot" }
protobuf-plugin = { group = "com.google.protobuf", name = "protobuf-gradle-plugin", version.ref = "protobuf-plugin" }
gatling-plugin = { group = "gradle.plugin.io.gatling.gradle", name = "gatling-gradle-plugin", version.ref = "gatling-plugin" }
dependencyVersions-plugin = { group = "com.github.ben-manes", name = "gradle-versions-plugin", version.ref = "dependencyVersions-plugin" }
errorprone-core = { group = "com.google.errorprone", name = "error_prone_core", version.ref = "errorprone" }
errorprone-plugin = { group = "net.ltgt.errorprone", name = "net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-plugin" }
nullaway = { group = "com.uber.nullaway", name = "nullaway", version.ref = "nullaway" }
spotbugs = { group = "com.github.spotbugs", name = "spotbugs", version.ref = "spotbugs" }
spotbugs-plugin = { group = "com.github.spotbugs.snom", name = "spotbugs-gradle-plugin", version.ref = "spotbugs-plugin" }
spotbugs-findsecbugs-plugin = { group = "com.h3xstream.findsecbugs", name = "findsecbugs-plugin", version.ref = "spotbugs-findsecbugs-plugin" }
spotbugs-fbContrib-plugin = { group = "com.mebigfatguy.fb-contrib", name = "fb-contrib", version.ref = "spotbugs-fbContrib-plugin" }
helm-plugin = { group = "com.citi.gradle-plugins.helm", name = "helm-plugin", version.ref = "helm-plugin" }
helm-releases-plugin = { group = "com.citi.gradle-plugins.helm", name = "helm-releases-plugin", version.ref = "helm-plugin" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
